sudo: required

language: c

services:
  - docker

matrix:
  include:
  - env: IMG=quid2/eta CMD="etlas update;etlas test"

  ##- env: IMG=quid2/x64-ubuntu-ghcjs CMD="stack test --stack-yaml stack-ghcjs.yaml"

  ##- env: IMG=quid2/x64-ubuntu-ghcjs-9.21 CMD="stack test --stack-yaml stack-ghcjs-9.21.yaml"

  # - env: IMG=quid2/x32-ubuntu-cabal CMD="cabal v2-build --only-dependencies --enable-tests;cabal v2-build;cabal v2-test"

  # - env: IMG=quid2/x64-ubuntu-stack-lts-6.35 CMD="stack test --resolver lts-6.35"

  # - env: IMG=quid2/x64-ubuntu-stack-lts-9.21 CMD="stack test --resolver lts-9.21"

  # - env: IMG=quid2/x64-ubuntu-stack-lts-11.22 CMD="stack test --resolver lts-11.22"

  - env: IMG=quid2/x64-ubuntu-stack-lts-12.26 CMD="stack test --resolver lts-12.26"

  - env: IMG=quid2/x64-ubuntu-stack-lts-13.22 CMD="stack test --resolver lts-13.22"

before_install:
- docker pull $IMG

script:
- PKG=zm-language
- docker run -it $IMG bash -c "git clone https://github.com/Quid2/$PKG;cd $PKG;$CMD"
