resolver: lts-14.27

packages:
  - "."

extra-deps:
  - model-0.5
  - flat-0.4.4

  #- ../zm
  - github: Quid2/zm
    commit: c3e479e93233c87c86c64e383e5e302bc9207e11
  #- zm-0.3.2

  - megaparsec-7.0.5

  - Unique-0.4.7.6
  - tasty-quickcheck-0.10.1
